### ISSUE TITLE
Hi ，I couldnt find train_new.json 

### ISSUE THREAD

**Issue by herbertchen1** [abhipec/fnet#2]
There is only train.json in AFET

**Comment by abhipec** [comment]
train_new.json will be generated after running the data processor code shared in AFET repository. 

If there is a need to directly use the data used in "Fine-Grained Entity Type Classification by Jointly Learning Representations and Label Embeddings", TFRecord data files are available as mentioned at https://github.com/abhipec/fnet#data

Otherwise, the data processing step I followed was:
1. Run AFET data processer script.
2. Sanitize the processed data to remove some erroneous mentions.
3. Use the sanitized data for training. 

Also, an updated version of code, which does not requires these prepossessing is available at : https://github.com/abhipec/FgEC.

Hope this helps.

**Comment by herbertchen1** [comment]
> train_new.json will be generated after running the data processor code shared in AFET repository.
> 
> If there is a need to directly use the data used in "Fine-Grained Entity Type Classification by Jointly Learning Representations and Label Embeddings", TFRecord data files are available as mentioned at https://github.com/abhipec/fnet#data
> 
> Otherwise, the data processing step I followed was:
> 
> 1. Run AFET data processer script.
> 2. Sanitize the processed data to remove some erroneous mentions.
> 3. Use the sanitized data for training.
> 
> Also, an updated version of code, which does not requires these prepossessing is available at : https://github.com/abhipec/FgEC.
> 
> Hope this helps.

Thanks very much!! last night I've found the train_new.json
The test set have some error :
1. some mentions are missing .
2. some mentions  are dupillicate.
According to your code ,there is actually 12845 mentions. So i should use this 12845 mention to be my test set??

**Comment by abhipec** [comment]
> The test set have some error 

There were some duplicates as well some zero length entity mentions. I will check and get back on this issue.

**Comment by herbertchen1** [comment]
Thanks very much. I've got the train_new.json and run the preprocess script of sanitize.  If you have any need , please tell me

**Comment by abhipec** [comment]
Yes, I verified. After running the sanitizer script, the resulting entity mention were 12845. I am closing this issue. If there any other query, I will be happy to help. Please open this or a new issue in that case.
